<?php

namespace Database\Seeders;

use App\Models\Employee;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

/**
 * The client's "201 Files" Employee Master File export — personal details,
 * addresses, and emergency contacts for the 25xxx-coded roster. Matched by
 * employee_code, separate from the EMP-00xx demo roster and the older
 * 3-digit codes in RealEmployeeSeeder (which predate this export and cover
 * a handful of the same people under a different code).
 */
class EmployeeMasterFileSeeder extends Seeder
{
    /**
     * @return list<array<string, mixed>>
     */
    public static function employees(): array
    {
        return [
            ['code' => '25150', 'last' => 'Marin', 'first' => 'Mark Anthony', 'middle' => 'P.', 'gender' => 'male', 'civil' => 'married', 'dob' => '5-Mar-1992', 'pob' => 'Manila', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'company_email' => 'marzankwmanagementservices@gmail.com', 'status' => 'active'],
            ['code' => '25151', 'last' => 'Perez', 'first' => 'Arjeleen', 'photo' => 'https://drive.google.com/file/d/1po1vrdGZIYPR6X_Lz3vH4i3lEVtNz5f-/view?usp=sharing', 'gender' => 'female', 'civil' => 'single', 'dob' => '17-Mar-1995', 'pob' => 'Manila', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'company_email' => 'marzankwmanagementservices@gmail.com', 'status' => 'active'],
            ['code' => '25152', 'last' => 'Dela Cruz', 'first' => 'Efren', 'middle' => 'H.', 'photo' => 'https://drive.google.com/file/d/1d8qBNy0dNjlr8lJVnAG8-2j_mP4VhPIc/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '14-Apr-1968', 'pob' => 'Quezon', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '205 Copper st. BLK 4 LOT 5 Brgy. E. Malia G.M.A. Cavite', 'ec_name' => 'Milagros Banat', 'ec_number' => '09637763852', 'ec_rel' => 'Live in Partner', 'status' => 'active'],
            ['code' => '25153', 'last' => 'Anas', 'first' => 'Ramon', 'photo' => 'https://drive.google.com/file/d/13oADzrSkB9lMyqzdZjPZKzTlTbrqtrBb/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '19-Apr-1980', 'pob' => 'Dao, Capiz', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '9300716727', 'personal_email' => 'ramonanas.019@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'BLK F13 LOT 1, San Lorenzo Rull Dasmarinas Cavite', 'permanent' => 'BLK F13 LOT 1, San Lorenzo Rull Dasmarinas Cavite'],
            ['code' => '25154', 'last' => 'Belen', 'first' => 'Jonathan', 'photo' => 'https://drive.google.com/file/d/13CtpPO-AQIVVWI99QSJ6VR0BJXFElqWy/view?usp=sharing', 'gender' => 'male', 'dob' => '16-Jun-1974', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09460507993', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'BLCK 44 LOT 28 PHASE 1 S.V.5.A BRGY. LANGKIWA BINAN CITY LAGUNA', 'permanent' => 'BLCK 44 LOT 28 PHASE 1 S.V.5.A BRGY. LANGKIWA BINAN CITY LAGUNA', 'ec_name' => 'Vilma Belen', 'ec_number' => '09460507993', 'ec_rel' => 'Wife', 'status' => 'active'],
            ['code' => '25155', 'last' => 'Dela Cruz', 'first' => 'Jayvee', 'photo' => 'https://drive.google.com/file/d/1yMGc0KVAhWMNaXDmk1NFy0dFX_wVtdvA/view?usp=sharing', 'gender' => 'male', 'dob' => '16-Jun-1996', 'pob' => 'Anoling Pinamalayan oriental mindoro', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09386486918', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'BLCK 33 LOT 18 PALIPARAN II, DASMARINAS, CAVITE', 'permanent' => 'Anoling Pinamalayan Orientall Mindoro', 'ec_name' => 'Efren Dela Cruz', 'ec_rel' => 'Father'],
            ['code' => '25156', 'last' => 'Lopez', 'first' => 'Mary grace', 'middle' => 'M.', 'photo' => 'https://drive.google.com/file/d/1Mrbmv4w7NGbfjsIkOIdb0Z7p9TKlzIH0/view?usp=sharing', 'gender' => 'female', 'nat' => 'Filipino', 'contact' => '09922986581', 'personal_email' => 'dadamagdalita31@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com'],
            ['code' => '25157', 'last' => 'Bolinan', 'first' => 'Mark', 'photo' => 'https://drive.google.com/file/d/1yrQTbUuEJlM46-S7Z754CL2_F2pWz8wX/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '7-Jan-2000', 'pob' => 'Dasmarinas Cavite', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09925344822', 'personal_email' => 'Marchjhonasb@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Bio L2 PH2 mabuhay homes 2000 paliparan II Dasmarinas Cavite', 'permanent' => 'Bio L2 PH2 mabuhay homes 2000 paliparan II Dasmarinas Cavite', 'ec_name' => 'Reynalene Octa', 'ec_number' => '0936422234', 'ec_rel' => 'Live in Partner', 'status' => 'active'],
            ['code' => '25158', 'last' => 'Angelo', 'first' => 'Mark Joseph', 'middle' => 'C.', 'photo' => 'https://drive.google.com/file/d/1TCyUY953B-oJ8qrn3fquGeDw7iiyyXTU/view?usp=sharing', 'gender' => 'male', 'dob' => '10-Jun-1998', 'pob' => 'GMA Cavite', 'nat' => 'Filipino', 'contact' => '9930627225', 'personal_email' => 'angelomarkjoseph98@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com'],
            ['code' => '25159', 'last' => 'Padilla', 'first' => 'Joemari', 'middle' => 'D.', 'photo' => 'https://drive.google.com/file/d/1XCIMHJz8ZtOHqsHqTOOP9FT3l9nNXPoF/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '3-Oct-1992', 'pob' => 'Anoling Pinamalayan Oriental Mindoro', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '9672774379', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '#300 Brgy. Sampalov 1, Dasmarinas Cavite', 'permanent' => 'Anoling Pinamalayan Oriental Mindoro', 'ec_name' => 'Manilyn Hernandez', 'ec_number' => '9384150544', 'ec_rel' => 'Wife', 'status' => 'active'],
            ['code' => '25160', 'last' => 'Corpuz', 'first' => 'Erika Mae', 'middle' => 'T.', 'photo' => 'https://drive.google.com/file/d/1O_GXZrPFNFW-XtlTs0dncmdXY9ePjU48/view?usp=sharing', 'gender' => 'female', 'civil' => 'married', 'dob' => '14-Dec-1997', 'pob' => 'Dasmarinas Cavite', 'nat' => 'Filipino', 'contact' => '09534231007', 'personal_email' => 'erickacorpuz142gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Block D16 Lot 23 Brgy. San Andres 2 Dasmarinas City Cavite'],
            ['code' => '25161', 'last' => 'Pascual', 'first' => 'Micheal Vincent', 'photo' => 'https://drive.google.com/file/d/14bR8WRMRsAr0GAVxoQMHnONIv7iNUzSR/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '3-Dec-1990', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09911974062', 'personal_email' => 'Vincentpascual@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Purok 7, Brgy. Mabini Lipa City, Batangas'],
            ['code' => '25162', 'last' => 'Coliat', 'first' => 'Exequiel', 'photo' => 'https://drive.google.com/file/d/1JOkj1k8-n5QWy4Y0WI5Bc3KZkTmop1Sb/view?usp=sharing', 'gender' => 'male', 'company_email' => 'marzankwmanagementservices@gmail.com'],
            ['code' => '25163', 'last' => 'Maderano', 'first' => 'Princess Nicole', 'gender' => 'female', 'civil' => 'single', 'company_email' => 'marzankwmanagementservices@gmail.com'],
            ['code' => '25164', 'last' => 'Gillaco', 'first' => 'Francisco', 'photo' => 'https://drive.google.com/file/d/1ME64aDZ1FIaAq6XJmAnXADK8IBukJlf5/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '9-Mar-1970', 'pob' => 'Calamba, Laguna', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '9387450581', 'personal_email' => 'gallicofrancisco@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '246 Mount Halcon Palingon Calamba Laguna Philippines', 'permanent' => '346 MT. Halcon st,.Palingon, City of Calamaba, laguna', 'ec_name' => 'Jennifer Gilacco', 'ec_number' => '09366479894', 'ec_rel' => 'wife', 'status' => 'active'],
            ['code' => '25165', 'last' => 'Maderazo', 'first' => 'Jimmar', 'photo' => 'https://drive.google.com/file/d/1GF_bnNnvyafwW8hWSZ4wHaHyEPrfGD8W/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '15-Feb-1985', 'pob' => 'Simlong, Batangas City', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09563975593', 'personal_email' => 'jhianjhay131@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Banaba South, Batangas City', 'ec_name' => 'Darlyn G. Maderazo', 'ec_number' => '09984246347', 'ec_rel' => 'Wife', 'status' => 'active'],
            ['code' => '25166', 'last' => 'De Guzman', 'first' => 'Victor', 'photo' => 'https://drive.google.com/file/d/1Vg8kOOMS1L0N9GUZv5WmCn02dN2sDeeF/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '9-Mar-1970', 'contact' => '0910996011', 'personal_email' => 'dgzmnvicor11@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '09 Rosal St. Dolor Subdivision Brgy. 6, Batangas City', 'permanent' => '09 Rosal St. Dolor Subdivision Brgy. 6, Batangas City', 'ec_name' => 'Lilibeth De Guzman', 'ec_number' => '09664363665', 'ec_rel' => 'Wife', 'status' => 'active'],
            ['code' => '25167', 'last' => 'Lasala', 'first' => 'Gian Paolo', 'photo' => 'https://drive.google.com/file/d/19RZ0BIozmUlyjew6a9n0qyPGK3nbEp_y/view?usp=sharing', 'gender' => 'male', 'personal_email' => 'lasalagianpaulo7@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com'],
            ['code' => '25168', 'last' => 'Mercado', 'first' => 'Anthony', 'photo' => 'https://drive.google.com/file/d/1peADlC-9TzaWTGfOefYIPeWXXyRpRU0l/view?usp=sharing', 'gender' => 'male', 'personal_email' => '1991mercadoantony@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com'],
            ['code' => '25169', 'last' => 'Del Pilar', 'first' => 'Don Jeric', 'photo' => 'https://drive.google.com/file/d/1RIerrA7IFdw3WxzGefxN_qOfCydZTHpl/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '14-Nov-1985', 'pob' => 'Nueva Ecija', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09916214205', 'personal_email' => 'donjeric.delpilar@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '3360 ME Milagrosa St. Capitol Homesite Subd. Cotta, Lucena City', 'permanent' => '3360 ME Milagrosa St. Capitol Homesite Subd. Cotta, Lucena City', 'ec_name' => 'Rosemarie Del Pilar', 'ec_number' => '09938667627', 'ec_rel' => 'Mother'],
            ['code' => '25170', 'last' => 'Salandanan', 'first' => 'John Armel', 'photo' => 'https://drive.google.com/file/d/1qn2rryBsSmdHhKs3a8jPf-Es-Y6KC5kU/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '28-Feb-1992', 'pob' => 'Brgy. Bignay 2, Sariaya, Quezon', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09177112802', 'personal_email' => 'johnarmelsalandanan@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '367 Sitio Sampaguita, Bignay 2, Sariaya, Quezon', 'permanent' => '367 Sitio Sampaguita, Bignay 2, Sariaya, Quezon', 'ec_name' => 'Marimel Rivarez Anaclor', 'ec_number' => '09215861289', 'ec_rel' => 'Step Sister', 'status' => 'active'],
            ['code' => '25171', 'last' => 'Delas Alas', 'first' => 'John Eric', 'photo' => 'https://drive.google.com/file/d/1ebVjygd33uR8xyY4K0oSa45LDe3RJgG2/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '8-Apr-2001', 'pob' => 'Lucena City', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09460908943', 'personal_email' => 'abadillajohneric@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Cm Recto St. Brgy. Angeles Zone 1', 'permanent' => 'Cm Recto St. Brgy. Angeles Zone 1', 'ec_name' => 'Nora Delas Alas', 'ec_number' => '09238660975', 'ec_rel' => 'Mother'],
            ['code' => '25172', 'last' => 'Delas Alas', 'first' => 'Rodel', 'photo' => 'https://drive.google.com/file/d/1RYDKTVYWSjkaBChV8-YNbjk7Rna-D3Ff/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '19-Nov-1977', 'pob' => 'Tayabas', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09238660975', 'personal_email' => 'delasalasrodel18@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Brgy. Angeles Zone 1, Tayabas City, Quezon Province', 'permanent' => 'Brgy. Angeles Zone 1, Tayabas City, Quezon Province', 'ec_name' => 'Nora Delas Alas', 'ec_number' => '09238660975', 'ec_rel' => 'Wife', 'status' => 'active'],
            ['code' => '25173', 'last' => 'Delos Reyes', 'first' => 'Romnick', 'photo' => 'https://drive.google.com/file/d/1W86wjdxWLdStjNiTJnBVSU8Gdap8Htfd/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '27-Aug-1990', 'pob' => 'Pagbilao Quezon', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09084290041', 'personal_email' => 'rommnnick27@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Brgy. Pinagbayanan, Pagbilao, Quezon', 'permanent' => 'Brgy. Pinagbayanan, Pagbilao, Quezon', 'ec_name' => 'Rosalina Delos Reyes', 'ec_number' => '/09635139436', 'ec_rel' => 'Mother', 'status' => 'active'],
            ['code' => '25174', 'last' => 'Gueriba', 'first' => 'Susan', 'photo' => 'https://drive.google.com/file/d/1MknRPkFmqgZbEKJqLNaPm7xN_CZws7QO/view?usp=sharing', 'gender' => 'female', 'civil' => 'widowed', 'dob' => '14-Dec-1981', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'personal_email' => 'endonilasusan@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Sitio 3, Barangay Mayuwi, Tayabas City', 'permanent' => 'Sitio 3, Barangay Mayuwi, Tayabas, Quezon'],
            ['code' => '25175', 'last' => 'Hernan', 'first' => 'Glynn', 'photo' => 'https://drive.google.com/file/d/1TlQMClIky1YyEjRsr4Gmvxx0KjjadWWr/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '26-Sep-1983', 'pob' => 'Lucena City', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09498685647', 'personal_email' => 'hermanglynn@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Purok maganda, angay compound, Brgy. Gulang-Gulang Lucena City Quezon 4301', 'permanent' => 'Purok maganda, angay compound, Brgy. Gulang-Gulang Lucena City Quezon 4301', 'ec_name' => 'Maria Luisa Arlene Clor', 'ec_number' => '09945077651', 'ec_rel' => 'Sister', 'status' => 'active'],
            ['code' => '25176', 'last' => 'Biclar', 'first' => 'Christian', 'photo' => 'https://drive.google.com/file/d/1VBS3p0RAB6rA_IDnGp3EyML9Vst-26-_/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '12-Oct-1999', 'pob' => 'Compostela, Cebu', 'rel' => 'Catholic', 'contact' => '09663776601', 'personal_email' => 'c2Itschristianmbiclar2cl@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '#316, BLK 8, Lot 37, Maryland Homes III Sub. Barangay San Vicente, San Pablo City, Laguna 4000', 'permanent' => '#316, BLK 8, Lot 37, Maryland Homes III Sub. Barangay San Vicente, San Pablo City, Laguna 4000', 'ec_name' => 'Fe Molina Biclar', 'ec_rel' => 'Mother'],
            ['code' => '25177', 'last' => 'Sanchez', 'first' => 'Zues Jay', 'photo' => 'https://drive.google.com/file/d/1UfyYvwbXjA9gkIKKfWBlMXBq21eVulAI/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '6-Jun-1995', 'pob' => 'San Pablo City', 'nat' => 'Filipino', 'rel' => 'Born Again', 'contact' => '0907755716', 'personal_email' => 'sanchezzeus77@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Brgy. 203 San Roque, San Pablo City, Laguna'],
            ['code' => '25178', 'last' => 'Tumaob', 'first' => 'Jonnel', 'photo' => 'https://drive.google.com/file/d/1ImEsZpm5pwTgROjn1X8dzRm9pyyjh-NX/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '11-Jun-1980', 'nat' => 'Filipino', 'rel' => 'Seventh Day Adventist', 'contact' => '09674307288', 'personal_email' => 'lennoj0611@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '1230 Sta. Clara Subd., Brgy. Sampaloc 2, Sariaya Quezon', 'permanent' => '1230 Sta. Clara Subd., Brgy. Sampaloc 2, Sariaya Quezon'],
            ['code' => '25179', 'last' => 'Panegrayo', 'first' => 'Eugine', 'photo' => 'https://drive.google.com/file/d/1OHNN2USy5RkJI0OpAG7fQxwvxK53WRrw/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '18-Oct-1995', 'pob' => 'San Pablo City, Laguna', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09279693550', 'personal_email' => 'panergayogene@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Brgy. Stmo. Rosarion, San Pablo City, Laguna', 'permanent' => 'Brgy. Stmo. Rosarion, San Pablo City, Laguna', 'ec_name' => 'Jessica Panergayo', 'ec_number' => '09930080920', 'ec_rel' => 'Wife'],
            ['code' => '25180', 'last' => 'Hapin', 'first' => 'Edwin', 'photo' => 'https://drive.google.com/file/d/1Jx6jNMG1tEl6El_kLtgd5wR63DFjM4YF/view?usp=sharing', 'gender' => 'male', 'civil' => 'single', 'dob' => '23-Jul-1989', 'pob' => 'Damarinas Cavite', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09271765186', 'personal_email' => 'hapinhedwin@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '4119 Brgy. Del Remedio, San Pablo City, Laguna', 'permanent' => 'Trece Martires, Casiguran Sorsogon', 'ec_name' => 'Haide Hapin', 'ec_rel' => 'Mother'],
            ['code' => '25181', 'last' => 'Lising', 'first' => 'Christian', 'photo' => 'https://drive.google.com/file/d/1bc8VWEQaRjBdonqsV8ZiDPIX-31HtOwM/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '8-Feb-1999', 'pob' => 'San Pablo City, Laguna', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09187722638', 'personal_email' => 'christianlising0208@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => '1058 Dulong Bayan St. Brgy. Bagong Bayan, San Pablo City, Laguna 4000', 'permanent' => '1058 Dulong Bayan St. Brgy. Bagong Bayan, San Pablo City, Laguna 4000', 'ec_name' => 'Genesis Aquino', 'ec_number' => '09518687837', 'ec_rel' => 'Wife'],
            ['code' => '25182', 'last' => 'Javier', 'first' => 'Jomar', 'photo' => 'https://drive.google.com/file/d/13bSQL19sKoOgCmdZBS3H39r-WL5729VB/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'dob' => '26-Mar-1991', 'pob' => 'Tiaong Quezon', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09669917838', 'personal_email' => 'javiercarlo0023@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Purok #2 Brgy, San Isidro San Pablo City, Laguna'],
            ['code' => '25183', 'last' => 'Paje', 'first' => 'Abigail', 'middle' => 'G.', 'gender' => 'female', 'civil' => 'married', 'dob' => '25-Sep-1995', 'pob' => 'Agoo, La Union', 'nat' => 'Filipino', 'rel' => 'Born Again Christian', 'contact' => '9971263840', 'personal_email' => 'pajegail79@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Almanza Uno Doctors Village, Las Pinas', 'permanent' => 'Pugo,La Union', 'status' => 'active'],
            ['code' => '25184', 'last' => 'Sumallo', 'first' => 'Dheo', 'middle' => 'M.', 'photo' => 'https://drive.google.com/file/d/1STOjLBkj7hwRjCfuCUviZeXDaQ5TEWOR/view?usp=sharing', 'gender' => 'male', 'civil' => 'married', 'contact' => '09298781881', 'personal_email' => 'dheosumalla07@gmail.com', 'company_email' => 'marzankwmanagementservices@gmail.com'],
            ['code' => '25185', 'last' => 'Joson', 'first' => 'Isagani', 'middle' => 'A.', 'gender' => 'male', 'civil' => 'married', 'dob' => '17-Apr-1983', 'pob' => 'Talisayan Sampaloc IV Dasmarinas Cavite', 'nat' => 'Filipino', 'contact' => '0970529806', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'Talisayan Sampaloc IV Dasmarinas Cavite', 'permanent' => '0235 Talisayan Sampaloc IV Dasmarinas Cavite', 'ec_name' => 'Ulta Joson', 'ec_number' => '9295584490', 'ec_rel' => 'Wife', 'status' => 'active'],
            ['code' => '25186', 'last' => 'Albina', 'first' => 'Julieto', 'middle' => 'T.', 'gender' => 'male', 'dob' => '27-Jun-1993', 'pob' => 'Pinana-an Lasnieves, Agusan del Norte', 'nat' => 'Filipino', 'rel' => 'Roman Catholic', 'contact' => '09914038005', 'company_email' => 'marzankwmanagementservices@gmail.com', 'current' => 'blk 5 lot 27 Bria Homes inocencio Trece Martirec City of Cavite'],
        ];
    }

    public function run(): void
    {
        foreach (static::employees() as $row) {
            Employee::query()->updateOrCreate(
                ['employee_code' => $row['code']],
                [
                    'first_name' => $row['first'],
                    'last_name' => $row['last'],
                    'middle_name' => $row['middle'] ?? null,
                    'photo_url' => $row['photo'] ?? null,
                    'gender' => $row['gender'] ?? null,
                    'marital_status' => $row['civil'] ?? null,
                    'date_of_birth' => isset($row['dob']) ? Carbon::createFromFormat('j-M-Y', $row['dob'])->toDateString() : null,
                    'place_of_birth' => $row['pob'] ?? null,
                    'nationality' => $row['nat'] ?? null,
                    'religion' => $row['rel'] ?? null,
                    'contact_number' => $row['contact'] ?? null,
                    'personal_email' => $row['personal_email'] ?? null,
                    'company_email' => $row['company_email'] ?? null,
                    'current_address' => $row['current'] ?? null,
                    'permanent_address' => $row['permanent'] ?? null,
                    'emergency_contact_name' => $row['ec_name'] ?? null,
                    'emergency_contact_number' => $row['ec_number'] ?? null,
                    'emergency_contact_relationship' => $row['ec_rel'] ?? null,
                    'status' => $row['status'] ?? 'active',
                ]
            );
        }
    }
}
